name: Welcome New Contributor

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Welcome and thanks for opening your first issue! We're excited to have you here 🎉
          pr-message: |
            🙌 Thanks for your first pull request! The team will review it soon. Welcome aboard 🚀
